[package]
name = "syscall"
version = "0.1.0"
edition = "2021"
<<<<<<< HEAD
=======
authors = ["YdrMaster <ydrml@hotmail.com>"]
>>>>>>> master

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
<<<<<<< HEAD

[features]
supervisor = []
=======
spin = "0.9.4"

[features]
kernel = []
>>>>>>> master
user = []
